# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_itemcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcomment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='itemcomment',
            name='item',
        ),
        migrations.DeleteModel(
            name='ItemComment',
        ),
    ]
