# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_itemfield_use_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfield',
            name='use_as_customer_filter',
            field=models.BooleanField(default=None),
        ),
    ]
