# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20180802_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfieldtypevalue',
            name='unique_str_id',
            field=models.CharField(default='09e509', max_length=10),
        ),
    ]
