# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_itemfieldtypevalue_unique_str_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfieldtypevalue',
            name='unique_str_id',
            field=models.CharField(default='af26c8', editable=False, max_length=10),
        ),
    ]
