# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20180803_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfieldtypevalue',
            name='unique_str_id',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
