# Generated by Django 2.0.5 on 2018-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20180807_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfielditem',
            name='use_as_common_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemfielditem',
            name='use_as_customer_filter',
            field=models.BooleanField(default=False),
        ),
    ]
