# Generated by Django 2.0.5 on 2018-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20180812_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfield',
            name='use_for',
        ),
        migrations.AddField(
            model_name='itemfieldtitle',
            name='use_for',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
