# Generated by Django 2.0.5 on 2018-08-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20180813_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfieldtypevalue',
            name='field_type',
        ),
    ]
