# Generated by Django 2.0.5 on 2018-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_remove_itemfieldtypevalue_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfieldtitle',
            name='use_for',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
