# Generated by Django 2.0.5 on 2018-08-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_auto_20180813_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='as_main',
            field=models.BooleanField(default=False),
        ),
    ]
