# Generated by Django 2.0.5 on 2018-08-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_itemimage_as_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
