# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_fl_name', models.CharField(default=None, max_length=100)),
                ('customer_login', models.CharField(default=None, max_length=100, unique=True)),
                ('customer_email', models.CharField(default=None, max_length=100, unique=True, validators=[django.core.validators.EmailValidator])),
                ('customer_phone', models.PositiveIntegerField(default=None)),
                ('customer_address', models.CharField(default=None, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Customer',
                'db_table': 'Customer',
            },
        ),
    ]
