# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180528_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
