# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180528_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
