# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180610_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
