# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_field',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
