# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filters',
            field=models.BooleanField(default=None),
        ),
    ]
