# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20180519_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
