# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180527_2238'),
        ('cart', '0002_remove_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
