# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0007_itemfield_use_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_update_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-order_update_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(blank=True, default=None)),
                ('payment_param', models.TextField()),
                ('payment_datetime', models.DateTimeField(auto_now_add=True)),
                ('payment_currency', models.TextField(default=None)),
                ('payment_status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='status.Status')),
            ],
            options={
                'verbose_name_plural': 'Payment',
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('shipment_param', models.TextField()),
                ('shipment_detail', models.TextField(default=None)),
                ('shipment_status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='status.Status')),
            ],
            options={
                'verbose_name_plural': 'Shipment',
                'db_table': 'Shipment',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items_in_order',
            field=models.ManyToManyField(through='order.OrderItem', to='item.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipment'),
        ),
        # migrations.AddField(
        #     model_name='order',
        #     name='order_status',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status'),
        # ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set([('item', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('order_id', 'customer')]),
        ),
    ]
