# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180614_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(blank=True, choices=[(0, 'DELIVERY_SERVICE_1'), (1, 'DELIVERY_SERVICE_2'), (2, 'DELIVERY_SERVICE_3')], default=None, max_length=50, null=True),
        ),
    ]
