# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180614_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('to_door', models.BooleanField(default=False)),
                ('to_pickUp_point', models.BooleanField(default=False)),
                ('to_anywhere_else', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
