# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180614_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.DeliveryService'),
        ),
    ]
