# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180614_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_in_order',
        ),
    ]
